Repository 2025-DSWU-CS-FP/EYEDIA_MODEL, pull requests merged in 2025-09, with the labels that each got.

#61 ♻️ Refactor: 백엔드 통신 재개발
  scripts/api/main.py
Labels: ✨ feature, ♻️ refactoring

#69 🐛 Api 불일치 수정
  scripts/api/main.py
Labels: 🐞 bug

#70 🐛 Fix: Query import 추가
  scripts/api/main.py
Labels: 🐞 bug

#73 ♻️ Api: /process-image q변수로 받으면 해당하는 data 반환하도록 수정
  scripts/api/main.py
Labels: ✨ feature, 🔧chore, ♻️ refactoring
